export const vinicolas = [
  {
    nombre: "Viñedos Santa Mónica",
    facebook: "https://www.facebook.com/VinedoSantaMonica",
    instagram: "https://www.instagram.com/vinedosantamonica/",
    paginaweb: "https://www.vinedosantamonica.com/",
  },
  {
    nombre: "Viñedos Tierra Tinta",
    facebook: "https://www.facebook.com/TierraTintaAguascalientes",
    instagram: "https://www.instagram.com/vinedostierratinta/",
    paginaweb: "https://tierratinta.com/",
  },
  {
    nombre: "Vinícola Santossca",
    facebook:
      "https://www.facebook.com/people/Vinicola-Santossca/100063567895216/",
    instagram: "https://www.instagram.com/vinicolasantossca/",
    paginaweb: "",
  },
  {
    nombre: "Bodegas de la Parra",
    facebook: "https://www.facebook.com/bodegasdelaparra",
    instagram: "https://www.instagram.com/bodegasdelaparra/",
    paginaweb: "https://bodegasdelaparra.com/",
  },
  {
    nombre: "Viñedos Casa Leal",
    facebook: "https://www.facebook.com/VinedoCasaLeal",
    instagram: "https://www.instagram.com/vinedoscasaleal/",
    paginaweb: "https://www.megauva.com.mx/",
  },
  {
    nombre: "Bodegas Origen",
    facebook: "https://www.facebook.com/BodegasOrigen",
    instagram: "https://www.instagram.com/bodegasorigen/",
    paginaweb: "",
  },
  {
    nombre: "Vinicola Iberia",
    facebook: "https://www.facebook.com/vinosiberia",
    instagram: "https://www.instagram.com/vinosiberia.mx/",
    paginaweb: "https://xn--viedosiberia-bhb.com/",
  },
  {
    nombre: "Vinicola el Aguaje",
    facebook: "https://www.facebook.com/VinicolaElAguaje/",
    instagram: "https://www.instagram.com/vinicola_elaguaje/",
    paginaweb: "https://vinicolaelaguaje.mx/",
  },
  {
    nombre: "Vinicola Santa Elena",
    facebook: "https://www.facebook.com/VinicolaSantaElena",
    instagram: "https://www.instagram.com/vinicolasantaelena/",
    paginaweb: "http://vinicolasantaelena.com/index_.html",
  },
  {
    nombre: "Viña Las Cruces",
    facebook: "https://www.facebook.com/vinalascruces",
    instagram: "https://www.instagram.com/vinalascruces.ags/",
    paginaweb: "https://vinalascruces.com/",
  },
  {
    nombre: "Viñedos y Bodegas Hacienda de Letras",
    facebook: "https://www.facebook.com/haciendadeletras/",
    instagram: "https://www.instagram.com/haciendadeletrasoficial/",
    paginaweb: "https://www.haciendadeletras.com/",
  },
  {
    nombre: "Viña Santa Julia",
    facebook: "https://www.facebook.com/profile.php?id=100069581864980",
    instagram: "",
    paginaweb: "",
  },
  {
    nombre: "Vinícola El Secreto",
    facebook: "https://www.facebook.com/VinicolaElSecreto",
    instagram: "https://www.instagram.com/vinicolaelsecreto.ags/",
    paginaweb: "http://www.vinicolaelsecreto.com/",
  },
  {
    nombre: "Viñedos El Potrerito",
    facebook: "",
    instagram: "https://www.instagram.com/vinedoselpotrerito/",
    paginaweb: "",
  },
  {
    nombre: "Viñedos Cuatro Soles La Aurora",
    facebook: "https://www.facebook.com/VinoCuatroSoles",
    instagram: "https://www.instagram.com/vinoscu4trosoles/",
    paginaweb: "https://vinoscuatrosoles.com/",
  },
  {
    nombre: "Vinícola FraGue",
    facebook: "https://www.facebook.com/VinicolaFraGue",
    instagram: "https://www.instagram.com/vinicola.frague/",
    paginaweb: "http://www.vinicolafrague.com/",
  },
  {
    nombre: "Vinícola Chacón",
    facebook: "https://www.facebook.com/vitiviniculturachacon",
    instagram: "https://www.instagram.com/vinicola_chacon/",
    paginaweb: "",
  },
  {
    nombre: "Vinicola Hasen",
    facebook: "https://www.facebook.com/profile.php?id=100057342255360",
    instagram: "https://www.instagram.com/vinicolahasen/",
    paginaweb: "",
  },
  {
    nombre: "Vinícola Casa de Quesada",
    facebook: "https://www.facebook.com/casadequesadamx",
    instagram: "https://www.instagram.com/casadequesadamx/",
    paginaweb: "http://casadequesada.com/",
  },
  {
    nombre: "Finca Renacimiento",
    facebook: "https://www.facebook.com/FincaRenacimiento/",
    instagram: "https://www.instagram.com/fincarenacimiento/",
    paginaweb: "",
  },
  {
    nombre: "Praon de María",
    facebook: "https://www.facebook.com/PraonDeMaria",
    instagram: "https://www.instagram.com/vinedospraon/",
    paginaweb: "http://www.praondemaria.com/",
  },
  {
    nombre: "Vinos Anonimo",
    facebook: "https://www.facebook.com/TintoAnonimo",
    instagram: "https://www.instagram.com/vinosanonimo/",
    paginaweb: "https://www.anonimovinos.com/",
  }
  ,
  {
    nombre: "Somms 8",
    facebook: "https://www.facebook.com/somms8",
    instagram: "https://www.instagram.com/somms8/",
    paginaweb: "https://somms8.com/",
  },
  {
    nombre: "Somos Vino",
    facebook: "https://www.facebook.com/vinosalsacia",
    instagram: "https://www.instagram.com/somos.vino/",
    paginaweb: "https://somosvino.shop/",
  },
  {
    nombre: "Vinicola del Rocio",
    facebook: "https://www.facebook.com/profile.php?id=61566828197515",
    instagram: "https://www.instagram.com/somos.vino/",
    paginaweb: "",
  },
  {
    nombre: "Cosecha 3",
    facebook: "https://www.facebook.com/profile.php?id=100054742871175",
    instagram: "https://www.instagram.com/cosechatres/",
    paginaweb: "",
  },
  {
    nombre: "Kasa Xawat",
    facebook: "https://www.facebook.com/profile.php?id=100063576185375",
    instagram: "https://www.instagram.com/kasa_xawat/",
    paginaweb: "https://linki.to/kasa-xawat",
  },
  {
    nombre: "Casa de Quino",
    facebook: "https://www.facebook.com/profile.php?id=61564512489884",
    instagram: "https://www.instagram.com/casadequino/",
    paginaweb: "https://casadequino.com/",
  },
  {
    nombre: "Vinicola Bonart",
    facebook: "https://www.facebook.com/bodegas.bonart",
    instagram: "https://www.instagram.com/bodegas.bonart/",
    paginaweb: "https://www.bodegasbonart.com/",
  },
  {
    nombre: "Viña Estacion",
    facebook: "https://www.facebook.com/utnaoficial",
    instagram: "https://www.instagram.com/utnags/",
    paginaweb: "https://sites.google.com/utna.edu.mx/somosvid/inicio",
  }
];