export const vinicolas = [
  {
    nombre: "Vinícola Amelia",
    facebook: "https://www.facebook.com/VinicolaAmelia/",
    instagram: "https://www.instagram.com/vinicola_amelia/?hl=es",
    paginaweb: "https://vinicolaamelia.com/",
  },
  {
    nombre: "Vinícola Pasado Meridiano",
    facebook: "https://www.facebook.com/VinosPasadoMeridiano/",
    instagram: "https://www.instagram.com/vinospasadomeridiano/",
    paginaweb: "",
  },
  {
    nombre: "Viñedos Cavall 7",
    facebook: "https://www.facebook.com/Cavall7",
    instagram: "https://www.instagram.com/cavall7/",
    paginaweb: "http://cavall7.com/",
  },
  {
    nombre: "Bodegas Pinesque",
    facebook: "https://www.facebook.com/pinesque",
    instagram: "https://www.instagram.com/pinesque/",
    paginaweb: "https://www.pinesque.com/",
  },
  {
    nombre: "Viñedo El Molino Don Tomás",
    facebook: "https://www.facebook.com/profile.php?id=100063510014674",
    instagram: "https://www.instagram.com/molinodontomas/",
    paginaweb: "https://elmolinodontomas.mx/",
  },
  {
    nombre: "Viñedos Ciénega de Castilla",
    facebook: "https://www.facebook.com/profile.php?id=100054982734130",
    instagram: "https://www.instagram.com/vinedocienegadecastilla/",
    paginaweb: "https://www.vinedocienegadecastilla.com/",
  },
  {
    nombre: "Viñedo Cuarto Linaje",
    facebook: "https://www.facebook.com/vinoscuartolinaje?mibextid=LQQJ4d",
    instagram: "https://www.instagram.com/cuartolinaje/",
    paginaweb: "",
  },
  {
    nombre: "Viñedos Palomino",
    facebook: "https://www.facebook.com/profile.php?id=100063671645360",
    instagram: "https://www.instagram.com/marroc_vinedospalomino/",
    paginaweb: "",
  },
  {
    nombre: "Viñedos Alta Mira",
    facebook: "https://www.facebook.com/profile.php?id=100063211630354",
    instagram: "https://www.instagram.com/altamira_vinedo/",
    paginaweb: "",
  },
  {
    nombre: "Viñedos Tres Rios",
    facebook: "https://www.facebook.com/RutaTresRios",
    instagram: "https://www.instagram.com/rutatresrios/",
    paginaweb: "",
  },
  {
    nombre: "Viñedos Encinillas",
    facebook: "https://www.facebook.com/Encinillas/?fref=ts",
    instagram: "https://www.instagram.com/encinillas/",
    paginaweb: "https://vinosencinillas.com/",
  },
  {
    nombre: "Viñedos Mision",
    facebook: "https://www.facebook.com/vinosmision",
    instagram: "https://www.instagram.com/vinos.mision/",
    paginaweb: "https://vinosmision.com/",
  },
  {
    nombre: "Vinicola Diez Gonzalez",
    facebook: "https://www.facebook.com/vinicoladiezgonzalez",
    instagram: "https://www.instagram.com/vinicola_diez_gonzalez/",
    paginaweb: "https://vinicoladiezgonzalez.com.mx/",
  },
  {
    nombre: "Casa Establo",
    facebook: "https://www.facebook.com/casaestablo/",
    instagram: "https://www.instagram.com/casa_establo/",
    paginaweb: "",
  },
  {
    nombre: "Viñedo los Portales",
    facebook: "https://www.facebook.com/profile.php?id=100092109847306",
    instagram: "https://www.instagram.com/losportalesvinedo/",
    paginaweb: "",
  },
  {
    nombre: "Piñamora",
    facebook: "https://www.facebook.com/profile.php?id=100092109847306",
    instagram: "https://www.instagram.com/pinamoravino/?hl=es",
    paginaweb: "https://pinamora.com/",
  },
  {
    nombre: "Turbina",
    facebook: "https://www.facebook.com/vinedoslaturbina",
    instagram: "https://www.instagram.com/vinedoslaturbina",
    paginaweb: "https://www.laturbina.mx/",
  },
  {
    nombre: "Vinicola la Victoria",
    facebook: "https://www.facebook.com/profile.php?id=61563444338874&locale=es_LA",
    instagram: "https://www.instagram.com/vinicola_lavictoria",
    paginaweb: "",
  },
  {
    nombre: "Cava Baltierra",
    facebook: "https://www.facebook.com/CavaBaltierra",
    instagram: "",
    paginaweb: "",
  },
  {
    nombre: "Viñedos Santa Clara",
    facebook: "https://www.facebook.com/VinosSantaClaraSAdeCV",
    instagram: "https://www.instagram.com/vinossantaclarasadecv/",
    paginaweb: "https://vinossantaclara.com/",
  },
  {
    nombre: "Vinicola Casa Chavez",
    facebook: "https://www.facebook.com/VinicolaCasaChavez",
    instagram: "https://www.instagram.com/vinicolacasachavez/",
    paginaweb: "",
  },
  {
    nombre: "Vitivinicola Richesse",
    facebook: "https://www.facebook.com/profile.php?id=100063564831759",
    instagram: "",
    paginaweb: "",
  },
  {
    nombre: "Bodegas Villalpando",
    facebook: "https://www.facebook.com/BodegasVallesVillalpando",
    instagram: "https://www.instagram.com/bodegasvallesvillalpando/",
    paginaweb: "https://bodegasvallesvillalpando.com/",
  },
  {
    nombre: "Casa Elica",
    facebook: "https://www.facebook.com/casaelica",
    instagram: "https://www.instagram.com/casaelica/",
    paginaweb: "",
  },
  {
    nombre: "Casa Vazqueño",
    facebook: "https://www.facebook.com/profile.php?id=61562556882132",
    instagram: "https://www.instagram.com/vinedocasavazqueno",
    paginaweb: "https://www.casavazqueno.com/",
  }
];
