export const vinicolas = [
  {
    nombre: "Viñedos Blanc",
    facebook: "https://www.facebook.com/vinedosblanc",
    instagram: "https://www.instagram.com/vinedosblanc/",
    paginaweb: "https://www.xn--viedosblanc-2db.com/",
  },
  {
    nombre: "Bodega los Cedros",
    facebook: "https://www.facebook.com/bodegaloscedros/",
    instagram: "https://www.instagram.com/bodegaloscedros/",
    paginaweb: "https://bodegaloscedros.com/",
  },
  {
    nombre: "Bodegas del Viento",
    facebook: "https://www.facebook.com/Bodegasdelvientomx?ref=br_rs",
    instagram: "https://www.instagram.com/bodegasdelviento/",
    paginaweb: "https://bodegasdelviento.com/",
  },
  {
    nombre: "Vinos Don Leo",
    facebook: "https://www.facebook.com/vinosdonleo/?nr",
    instagram: "https://www.instagram.com/vinosdonleo/",
    paginaweb: "https://www.vinosdonleo.com/",
  },
  {
    nombre: "Bodega Barro Viejo",
    facebook: "https://www.facebook.com/BarroViejoParras",
    instagram: "https://www.instagram.com/barroviejoparras/",
    paginaweb: "https://barroviejo.com.mx/",
  },
  {
    nombre: "Bodega Las Pudencianas",
    facebook: "https://www.facebook.com/laspudencianas",
    instagram: "https://www.instagram.com/laspudencianas/",
    paginaweb: "https://www.laspudencianas.com/",
  },
  {
    nombre: "Vinícola Parvada",
    facebook: "https://www.facebook.com/parvadavinos/",
    instagram: "https://www.instagram.com/vinosparvada/",
    paginaweb: "https://vinosparvada.com/",
  },
  {
    nombre: "Casa Madero",
    facebook: "https://www.facebook.com/CasaMadero1597/",
    instagram: "https://www.instagram.com/casamadero/?hl=es-la",
    paginaweb: "https://madero.com/",
  },
  {
    nombre: "Bodegas Ferriño",
    facebook: "https://www.facebook.com/bodegasferrinooficial",
    instagram: "https://www.instagram.com/bodegasferrino/",
    paginaweb: "http://www.bodegasferrino.com.mx/",
  },
  {
    nombre: "Hacienda Florida Vinícola",
    facebook: "https://www.facebook.com/HaciendaFlorida",
    instagram: "https://www.instagram.com/haciendaflorida/",
    paginaweb: "https://haciendaflorida.com.mx/",
  },
  {
    nombre: "Bodegas Punto Norte",
    facebook: "https://www.facebook.com/VinosPuntoNorte",
    instagram: "https://www.instagram.com/vinospuntonorte/",
    paginaweb: "https://sites.google.com/view/bodegaspuntonorte/",
  },
  {
    nombre: "Camino Corazon",
    facebook: "https://www.facebook.com/CaminoCorazonCasaVinicola",
    instagram: "https://www.instagram.com/caminocorazon/",
    paginaweb: "https://caminocorazon.com.mx/",
  },
  {
    nombre: "Bodegas RGMX",
    facebook: "https://www.facebook.com/BodegaRGMX",
    instagram: "https://www.instagram.com/rgmx.mx",
    paginaweb: "https://rgmx.mx/",
  },
  {
    nombre: "Vinos los Pinos",
    facebook: "https://www.facebook.com/vinoslospinos",
    instagram: "https://www.instagram.com/vinoslospinos/",
    paginaweb: "https://www.vinoslospinos.com/",
  },
  {
    nombre: "Casa Naufrago",
    facebook: "https://www.facebook.com/casa.naufrago",
    instagram: "https://www.instagram.com/casanaufrago/",
    paginaweb: "https://www.casanaufrago.com",
  },
  {
    nombre: "Bodega Terra Serena",
    facebook: "https://www.facebook.com/bodegaterraserena.mx/",
    instagram: "https://www.instagram.com/bodegaterraserena.mx",
    paginaweb: "https://www.bodegaterraserena.mx/",
  },
  {
    nombre: "Vitali",
    facebook: "https://www.facebook.com/vinosvitalimexico",
    instagram: "https://www.instagram.com/vinosvitalimexico/",
    paginaweb: "https://vinosvitali.com.mx/",
  },
  {
    nombre: "Cuatro Angeles",
    facebook: "https://www.facebook.com/VinosCuatroAngeles",
    instagram: "https://www.instagram.com/vinoscuatroangeles/",
    paginaweb: "",
  },
  {
    nombre: "San Juan de la Vaqueria",
    facebook: "https://www.facebook.com/sanjuandelavaqueria",
    instagram: "https://www.instagram.com/vino_sanjuandelavaqueria/",
    paginaweb: "https://sanjuandelavaqueria.com/",
  },
  {
    nombre: "Conexion Ancestral",
    facebook: "https://www.facebook.com/VinicolaConexionAncestral",
    instagram: "https://www.instagram.com/vinicolaconexionancestral/",
    paginaweb: "",
  },
  {
    nombre: "Rancho el Fortin",
    facebook: "https://www.facebook.com/elfortinranch",
    instagram: "https://www.instagram.com/ranchoelfortin/",
    paginaweb: "https://www.ranchoelfortin.com/",
  }
];
