export const vinicolas = [
  {
    nombre: "Viñedos Guaname/Pájaro Azul",
    facebook: "https://www.facebook.com/profile.php?id=61556256360992",
    instagram: "https://www.instagram.com/bodegas_guaname/",
    paginaweb: "https://www.vinosguaname.com/",
  },
  {
    nombre: "Viñedo Cuna de Tierra",
    facebook: "https://www.facebook.com/vinoscunadetierra",
    instagram: "https://www.instagram.com/cunadetierra/",
    paginaweb: "https://www.cunadetierra.com/",
  },
  {
    nombre: "Tres Raíces",
    facebook: "https://www.facebook.com/vinicolatresraices/",
    instagram: "https://www.instagram.com/vinicolatresraices/",
    paginaweb: "https://xn--viedotresraices-zqb.com/",
  },
  {
    nombre: "Vinícola Toyan",
    facebook: "https://www.facebook.com/vinedo.toyan",
    instagram: "https://www.instagram.com/toyan_sanmigueldeallende/",
    paginaweb: "http://www.vinicolatoyan.com/",
  },
  {
    nombre: "Camino De Vinos",
    facebook: "https://www.facebook.com/CaminoDVinos",
    instagram: "https://www.instagram.com/caminodevinos/",
    paginaweb: "https://caminodevinos.com/",
  },
  {
    nombre: "Vinícola Octágono",
    facebook: "https://www.facebook.com/octagonovino",
    instagram: "https://www.instagram.com/octagonovinomx/",
    paginaweb: "https://www.elnidal.com.mx/octagono",
  },
  {
    nombre: "Hacienda San José Lavista",
    facebook: "https://www.facebook.com/HaciendaSanJoseLavista",
    instagram: "https://www.instagram.com/sanjoselavista/",
    paginaweb: "https://haciendasanjoselavista.com/",
  },
  {
    nombre: "Viñedos San Lucas",
    facebook: "https://www.facebook.com/vinedossanlucas",
    instagram: "https://www.instagram.com/vinedossanlucas/",
    paginaweb: "https://vinedossanlucas.com/",
  },
  {
    nombre: "Viñedo San Miguel",
    facebook: "https://www.facebook.com/vinedosanmiguel",
    instagram: "https://www.instagram.com/vinedosanmiguel/",
    paginaweb: "https://experiencias.vinedosanmiguel.com.mx/",
  },
  {
    nombre: "Dos Buhos",
    facebook: "https://www.facebook.com/dosbuhoswinery/",
    instagram: "https://www.instagram.com/vinedodosbuhos/",
    paginaweb: "https://www.dosbuhos.com/wine-tour/",
  },
  {
    nombre: "Bernat Vinicola",
    facebook: "https://www.facebook.com/BernatVinicola/",
    instagram: "https://www.instagram.com/bernat.vinicola/",
    paginaweb: "",
  },
  {
    nombre: "La Santisima Trinidad",
    facebook: "https://www.facebook.com/VinedosLaSantisimaTrinidad",
    instagram: "https://www.instagram.com/la.santisima.trinidad/",
    paginaweb: "https://www.lasantisimatrinidad.com.mx/",
  },
  {
    nombre: "VidElena",
    facebook: "https://www.facebook.com/profile.php?id=100063737902357",
    instagram: "https://www.instagram.com/videlena_vino/",
    paginaweb: "http://dolores-hidalgo.com/case/vid-elena/",
  },
  {
    nombre: "Viñedo Los Arcángeles",
    facebook: "https://www.facebook.com/vinedolosarcangeles/?locale=es_LA",
    instagram: "https://www.instagram.com/vinedolosarcangeles/?hl=es",
    paginaweb: "https://www.vinedolosarcangeles.com/",
  },
  {
    nombre: "Viñedo El Lobo",
    facebook: "https://www.facebook.com/vinicolalobo/?ref=br_rs",
    instagram: "https://www.instagram.com/vinedo_el_lobo/",
    paginaweb: "https://www.bodegalobo.com/",
  },
  {
    nombre: "Viñedo Dos Jacales",
    facebook: "https://www.facebook.com/profile.php?id=100090321391583",
    instagram: "",
    paginaweb: "",
  },
  {
    nombre: "Viñedo De Los Senderos",
    facebook: "https://www.facebook.com/senderossma/",
    instagram: "https://www.instagram.com/valledelossenderos_sma/",
    paginaweb: "https://vallelossenderos.com/",
  },
  {
    nombre: "Viñedo Puente Josefa",
    facebook: "https://www.facebook.com/PuenteJosefaVinedo",
    instagram: "https://www.instagram.com/puentejosefavino/",
    paginaweb: "https://puentejosefavinedo.com/",
  },
  {
    nombre: "Viñedos San Francisco",
    facebook: "https://www.facebook.com/vinedossanfrancisco/?locale=es_LA",
    instagram: "https://www.instagram.com/vinedossanfrancisco/",
    paginaweb: "https://www.vinedossanfrancisco.com/",
  },
  {
    nombre: "Vinos Babal",
    facebook: "https://www.facebook.com/vinobabal",
    instagram: "https://www.instagram.com/vinobabal/",
    paginaweb: "https://www.babal.mx/",
  },
  {
    nombre: "Hacienda San Bernardino",
    facebook: "http://facebook.com/HaciendaSanBernardin0/",
    instagram: "https://www.instagram.com/vinedoh_sanbernardino/",
    paginaweb: "https://haciendasanbernardino.com.mx/",
  },
  {
    nombre: "Vinicola el Paraiso",
    facebook: "https://www.facebook.com/vinicolaelparaiso",
    instagram: "https://www.instagram.com/vinicola_paraiso/",
    paginaweb: "",
  },
  {
    nombre: "Viña Gamar",
    facebook: "https://www.facebook.com/profile.php?id=61560929131224",
    instagram: "https://www.instagram.com/vinagamarmx/",
    paginaweb: "https://vinagamar.com/",
  },
  {
    nombre: "Viña del Gran Padre",
    facebook: "https://www.facebook.com/profile.php?id=100067812372443",
    instagram: "",
    paginaweb: "",
  },
  {
    nombre: "Cavas Manchon",
    facebook: "https://www.facebook.com/cavas.manchon.2025",
    instagram: "https://www.instagram.com/cavasmanchon",
    paginaweb: "https://enoturismo.cavasmanchon.com",
  },
  {
    nombre: "Casa JIX",
    facebook: "https://www.facebook.com/CasaJix",
    instagram: "https://www.instagram.com/casajix/",
    paginaweb: "https://www.casajix.com/",
  },
  {
    nombre: "Los Remedios",
    facebook: "https://www.facebook.com/LosRemediosRanchoYVinedos",
    instagram: "https://www.instagram.com/rancho_losremedios",
    paginaweb: "https://www.casajix.com/",
  },
  {
    nombre: "Finca Rosas",
    facebook: "https://www.facebook.com/fincarosas",
    instagram: "https://www.instagram.com/finca_rosas/",
    paginaweb: "",
  },
  {
    nombre: "Casa Anza",
    facebook: "",
    instagram: "",
    paginaweb: "https://www.casa-anza.mx/index.html",
  },
  {
    nombre: "Cava Garambullo",
    facebook: "",
    instagram: "https://www.instagram.com/cava_garambullo/",
    paginaweb: "",
  },
  {
    nombre: "Casa Reyes",
    facebook: "",
    instagram: "https://www.instagram.com/casareyes_mx/",
    paginaweb: "",
  },
  {
    nombre: "El Pavo Real",
    facebook: "https://www.facebook.com/elpavorealdelcampo/",
    instagram: "https://www.instagram.com/elpavorealdelcampo/?hl=es",
    paginaweb: "https://visitas.elpavoreal.com.mx/",
  },
  {
    nombre: "La Santa Vid",
    facebook: "http://facebook.com/LASANTAVID.SMA",
    instagram: "https://www.instagram.com/lasantavid/",
    paginaweb: "https://lasantavid.com/",
  },
  {
    nombre: "Viñedos Santa Catalina",
    facebook: "https://www.facebook.com/profile.php?id=100082880815072",
    instagram: "https://www.instagram.com/vinedossantacatalina",
    paginaweb: "https://tienda.vinedossanlucas.com/",
  },
  {
    nombre: "Viñedos Patria",
    facebook: "https://www.facebook.com/vinedospatriasma/",
    instagram: "https://www.instagram.com/vinedospatria/",
    paginaweb: "https://tienda.vinedossanlucas.com/",
  },
  {
    nombre: "Zirandaro",
    facebook: "https://www.facebook.com/ZirandaroSM",
    instagram: "https://www.instagram.com/zirandarosm/",
    paginaweb: "https://terrenos.zirandaro.com.mx/",
  },
  {
    nombre: "Viña del Cielo",
    facebook: "https://www.facebook.com/vinadelcielosma",
    instagram: "https://www.instagram.com/vinadelcielosma/",
    paginaweb: "https://www.vinadelcielo.net/",
  }
];
